version: '3.5'

services:
  app-frontend:
    container_name: apm-demo-app-frontend
    image: app-frontend
    build:
      context: app/frontend/
      args:
        - NGINX_VERSION=$NGINX_VERSION
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/log:/var/log/nginx
      - ./app/frontend/www:/usr/share/nginx/html:ro
    deploy:
      resources:
        limits:
          memory: 128M
      restart_policy:
        condition: always
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      - frontend

  app-middleware:
    container_name: apm-demo-app-middleware
    image: app-middleware
    build:
      context: app/middleware/
    deploy:
      resources:
        limits:
          memory: 128M
      restart_policy:
        condition: always
    environment:
      - ELASTIC_APM_SERVICE_NAME=elastic-apm-demo-middleware
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN}
    ports:
      - "3000:3000"          
    networks:
      - frontend
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      - external-service      

  external-service:
    container_name: apm-demo-external-service
    image: external-service
    build:
      context: app/external-service/
    deploy:
      resources:
        limits:
          memory: 128M
      restart_policy:
        condition: always
    environment:
      - ELASTIC_APM_SERVICE_NAME=elastic-apm-demo-external-service
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL}
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN}
    networks:
      - backend
      - database
    depends_on:
      - mongo     

  mongo:
    container_name: apm-demo-mongo
    image: mongo:$MONGODB_VERSION
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: apm-demo
    deploy:
      restart_policy:
        condition: always
    ports:
      - "27017:27017"          
    networks:
      - database

networks:
  frontend:
  backend:
  database:
